name: Snyk Security Scan
on:
  workflow_dispatch: {}

jobs:
  security-scan:
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'openrota'
    steps:
      - name: Checkout Code with Ref '${{ github.ref }}'
        uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
