name: Verify Build Workflow
on:
  push:
    paths-ignore:
      - '.dockerignore'
      - '.gitignore'
      - 'README*'
    branches: [main]
  pull_request:
    paths-ignore:
      - '.dockerignore'
      - '.gitignore'
      - 'README*'
    branches: [main]

jobs:
  verify-build:
    name: Verify Build
    runs-on: ubuntu-18.04
    if: github.repository_owner == 'shareNwork'
    steps:
      - name: Checkout Code with Ref '${{ github.ref }}'
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: Build Project
        run: make build-project

      - name: Login to DockerHub Registry
        if: github.event_name == 'push'
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Images for Docker.io
        if: github.event_name == 'push'
        env:
          IMAGE_TAG: "latest-snapshot"
        run: make build-image

      - name: List All The Images
        run: docker images

      - name: Push Images To Docker.io
        if: github.event_name == 'push'
        env:
          IMAGE_TAG: "latest-snapshot"
        run: make push-image
